from training.test_model import test_branches, test_TCP_branches
from training.train_model import train_branches, train_TCP_branches
from training.train import train_congestion_avoider
from training.test import test_congestion_avoider